// flow-typed signature: e514d679358d4cd5e32254350813c8fd
// flow-typed version: <<STUB>>/foreman_v2.0.0/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'foreman'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'foreman' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'foreman/forward' {
  declare module.exports: any;
}

declare module 'foreman/lib/colors' {
  declare module.exports: any;
}

declare module 'foreman/lib/console' {
  declare module.exports: any;
}

declare module 'foreman/lib/envs' {
  declare module.exports: any;
}

declare module 'foreman/lib/exporters' {
  declare module.exports: any;
}

declare module 'foreman/lib/forward' {
  declare module.exports: any;
}

declare module 'foreman/lib/proc' {
  declare module.exports: any;
}

declare module 'foreman/lib/procfile' {
  declare module.exports: any;
}

declare module 'foreman/lib/proxy' {
  declare module.exports: any;
}

declare module 'foreman/lib/requirements' {
  declare module.exports: any;
}

declare module 'foreman/nf' {
  declare module.exports: any;
}

declare module 'foreman/proxy' {
  declare module.exports: any;
}

// Filename aliases
declare module 'foreman/forward.js' {
  declare module.exports: $Exports<'foreman/forward'>;
}
declare module 'foreman/lib/colors.js' {
  declare module.exports: $Exports<'foreman/lib/colors'>;
}
declare module 'foreman/lib/console.js' {
  declare module.exports: $Exports<'foreman/lib/console'>;
}
declare module 'foreman/lib/envs.js' {
  declare module.exports: $Exports<'foreman/lib/envs'>;
}
declare module 'foreman/lib/exporters.js' {
  declare module.exports: $Exports<'foreman/lib/exporters'>;
}
declare module 'foreman/lib/forward.js' {
  declare module.exports: $Exports<'foreman/lib/forward'>;
}
declare module 'foreman/lib/proc.js' {
  declare module.exports: $Exports<'foreman/lib/proc'>;
}
declare module 'foreman/lib/procfile.js' {
  declare module.exports: $Exports<'foreman/lib/procfile'>;
}
declare module 'foreman/lib/proxy.js' {
  declare module.exports: $Exports<'foreman/lib/proxy'>;
}
declare module 'foreman/lib/requirements.js' {
  declare module.exports: $Exports<'foreman/lib/requirements'>;
}
declare module 'foreman/nf.js' {
  declare module.exports: $Exports<'foreman/nf'>;
}
declare module 'foreman/proxy.js' {
  declare module.exports: $Exports<'foreman/proxy'>;
}
