// flow-typed signature: b0f17adc053ab47ac8d46d9820949c87
// flow-typed version: <<STUB>>/hashmark_v4.1.0/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hashmark'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'hashmark' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hashmark/index' {
  declare module.exports: $Exports<'hashmark'>;
}
declare module 'hashmark/index.js' {
  declare module.exports: $Exports<'hashmark'>;
}
