// flow-typed signature: 98d59b4c4b707b6f21317454678175cd
// flow-typed version: <<STUB>>/md5_v2.2.1/flow_v0.40.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'md5'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'md5' {
  declare module.exports: (string | Buffer) => string;
}
