// flow-typed signature: e868cabcef8f49351f3dd48a1f4d42d9
// flow-typed version: <<STUB>>/multi-slider_v3.0.1/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'multi-slider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'multi-slider' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'multi-slider/lib/Handle' {
  declare module.exports: any;
}

declare module 'multi-slider/lib/index' {
  declare module.exports: any;
}

declare module 'multi-slider/lib/MultiSlider' {
  declare module.exports: any;
}

declare module 'multi-slider/lib/Track' {
  declare module.exports: any;
}

declare module 'multi-slider/lib/useTouches' {
  declare module.exports: any;
}

declare module 'multi-slider/src/Handle' {
  declare module.exports: any;
}

declare module 'multi-slider/src/index' {
  declare module.exports: any;
}

declare module 'multi-slider/src/MultiSlider' {
  declare module.exports: any;
}

declare module 'multi-slider/src/Track' {
  declare module.exports: any;
}

declare module 'multi-slider/src/useTouches' {
  declare module.exports: any;
}

// Filename aliases
declare module 'multi-slider/lib/Handle.js' {
  declare module.exports: $Exports<'multi-slider/lib/Handle'>;
}
declare module 'multi-slider/lib/index.js' {
  declare module.exports: $Exports<'multi-slider/lib/index'>;
}
declare module 'multi-slider/lib/MultiSlider.js' {
  declare module.exports: $Exports<'multi-slider/lib/MultiSlider'>;
}
declare module 'multi-slider/lib/Track.js' {
  declare module.exports: $Exports<'multi-slider/lib/Track'>;
}
declare module 'multi-slider/lib/useTouches.js' {
  declare module.exports: $Exports<'multi-slider/lib/useTouches'>;
}
declare module 'multi-slider/src/Handle.js' {
  declare module.exports: $Exports<'multi-slider/src/Handle'>;
}
declare module 'multi-slider/src/index.js' {
  declare module.exports: $Exports<'multi-slider/src/index'>;
}
declare module 'multi-slider/src/MultiSlider.js' {
  declare module.exports: $Exports<'multi-slider/src/MultiSlider'>;
}
declare module 'multi-slider/src/Track.js' {
  declare module.exports: $Exports<'multi-slider/src/Track'>;
}
declare module 'multi-slider/src/useTouches.js' {
  declare module.exports: $Exports<'multi-slider/src/useTouches'>;
}
