// flow-typed signature: e1572e3071e72fe282d888c3b2443d76
// flow-typed version: <<STUB>>/node-sass-module-importer_v0.1.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'node-sass-module-importer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'node-sass-module-importer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'node-sass-module-importer/index' {
  declare module.exports: $Exports<'node-sass-module-importer'>;
}
declare module 'node-sass-module-importer/index.js' {
  declare module.exports: $Exports<'node-sass-module-importer'>;
}
