// flow-typed signature: bbf20098811439b36ecd71373708f32b
// flow-typed version: <<STUB>>/redux-shortcuts_v0.0.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-shortcuts'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-shortcuts' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-shortcuts/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-shortcuts/lib/index.js' {
  declare module.exports: $Exports<'redux-shortcuts/lib/index'>;
}
