// flow-typed signature: dadd54947fd58a9e61095a92f84ba3b6
// flow-typed version: <<STUB>>/scrypt_v6.0.3/flow_v0.41.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scrypt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'scrypt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scrypt/node-scrypt-preinstall' {
  declare module.exports: any;
}

declare module 'scrypt/tests/scrypt-tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scrypt/index' {
  declare module.exports: $Exports<'scrypt'>;
}
declare module 'scrypt/index.js' {
  declare module.exports: $Exports<'scrypt'>;
}
declare module 'scrypt/node-scrypt-preinstall.js' {
  declare module.exports: $Exports<'scrypt/node-scrypt-preinstall'>;
}
declare module 'scrypt/tests/scrypt-tests.js' {
  declare module.exports: $Exports<'scrypt/tests/scrypt-tests'>;
}
